name: Update Hummingbird Packages

on:
  push:
    branches:
      main
  workflow_dispatch:

jobs:
  build:
    runs-on: macOS-latest
    strategy:
        matrix:
          repo:
            - hummingbird
            - hummingbird-auth
            - hummingbird-compression
            - hummingbird-fluent
            - hummingbird-lambda
            - hummingbird-postgres
            - hummingbird-valkey
            - hummingbird-websocket
            - postgres-migrations
            - swift-jobs
            - swift-jobs-valkey
            - swift-jobs-postgres
            - swift-mustache
            - swift-websocket
    steps:
    - name: App Token
      uses: tibdex/github-app-token@v2
      id: generate-token
      with:
        app_id: ${{ secrets.HB_APP_ID }}
        private_key: ${{ secrets.HB_APP_PRIVATE_KEY }}
    - name: Checkout Project Template
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        path: project-template
    - name: Checkout Target Repository
      uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 1
        path: ${{ matrix.repo }}
        repository: hummingbird-project/${{ matrix.repo }}
    - name: Install Dependencies
      run: |
        brew install mint
        mint install hummingbird-project/swift-mustache-cli
        echo "$HOME/.mint/bin" >> $GITHUB_PATH
    - name: Update Target Repository
      run: |
        cd project-template
        ./update.sh ../${{ matrix.repo }}
    - name: Set Commit message
      run: |
        cd project-template
        {
          echo 'GIT_COMMIT_MESSAGE<<EOF'
          git log -1 --pretty=medium
          echo EOF
        } >> "$GITHUB_ENV"
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ steps.generate-token.outputs.token }}
        path: ${{ matrix.repo }}
        commit-message: 'Update from hummingbird-project-template ${{ github.sha }}'
        committer: GitHub <noreply@github.com>
        author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
        branch: project-template-update
        title: 'Update from Hummingbird Project Template'
        body: |
          ${{ env.GIT_COMMIT_MESSAGE }}
          Automated update of files from https://github.com/hummingbird-project/hummingbird-project-template
        base: main
